name: Docker Image CI

on:
  push:
    branches: [ "prod" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dancexam-server:$(date +%s)
